from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json

# This secure connect bundle is autogenerated when you download your SCB,
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': 'secure-connect-victor-cassandra.zip'
}

# This token JSON file is autogenerated when you download your token,
# if yours is different update the file name below
with open("victor_cassandra-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

row = session.execute("select release_version from system.local").one()
if row:
  print(row[0])
else:
  print("An error occurred.")

print("-------------------------------------------------------")

session.set_keyspace('victorcass')

rows = session.execute("SELECT table_name FROM system_schema.tables WHERE keyspace_name='victorcass'")
    # Mostrar las tablas
print("Tablas en el keyspace 'victorcass':")
for row in rows:
  print(row.table_name)

print("-------------------------------------------------------")

rows = session.execute("SELECT * FROM cliente;")
print("Contenido de la tabla 'cliente':")
for row in rows:
    print(row)

print("-------------------------------------------------------")

session.execute("SELECT * FROM pedido WHERE pedido_id > 105 ALLOW FILTERING;")
rows = session.execute("SELECT * FROM pedido;")
for row in rows:
    print(row)

print("-------------------------------------------------------")